---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: go-echoserver
  namespace: product
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.chart-image: glob:0.1.*
spec:
  releaseName: go-echoserver
  chart:
    git: ssh://git@github.com/sermilrod/flux-repo
    ref: master
    path: charts/go-echoserver
  values:
    image: 
      repository: sermilrod/go-echoserver
      tag: 8fefdac9a910158c62f788e8a990f779e7ac0489
    resources:
      requests:
        memory: 32Mi
        cpu: 10m
      limits:
        memory: 64Mi
        cpu: 20m
